apiVersion: v1
kind: Service
metadata:
  name: frontend-service-4
spec:
  selector:
    app: lab4
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008 
